export const vegetables = [
  {
      "name": "大根",
      "calorie": 16,
      "vitamin_c": 10,
      "vitamin_a": 200,
      "fiber": 1.6,
  },
  {
      "name": "たまねぎ",
      "calorie": 40,
      "vitamin_c": 15,
      "vitamin_a": 200,
      "fiber": 1.8,
  },
  {
      "name": "にんじん",
      "calorie": 36,
      "vitamin_c": 7,
      "vitamin_a": 900,
      "fiber": 1.2,
  },
  {
      "name": "じゃがいも",
      "calorie": 77,
      "vitamin_c": 12,
      "vitamin_a": 70,
      "fiber": 2.0,
  },
  {
      "name": "キャベツ",
      "calorie": 26,
      "vitamin_c": 30,
      "vitamin_a": 60,
      "fiber": 1.8,
  },
  {
      "name": "ブロッコリー",
      "calorie": 34,
      "vitamin_c": 85,
      "vitamin_a": 700,
      "fiber": 2.8,
  },
  {
      "name": "ほうれん草",
      "calorie": 26,
      "vitamin_c": 100,
      "vitamin_a": 400,
      "fiber": 2.3,
  },
  {
      "name": "ピーマン",
      "calorie": 20,
      "vitamin_c": 20,
      "vitamin_a": 100,
      "fiber": 2.0,
  },
  {
      "name": "トマト",
      "calorie": 18,
      "vitamin_c": 18,
      "vitamin_a": 100,
      "fiber": 2.2,
  },
  {
      "name": "セロリ",
      "calorie": 15,
      "vitamin_c": 10,
      "vitamin_a": 20,
      "fiber": 1.4,
  },
  {
      "name": "きゅうり",
      "calorie": 12,
      "vitamin_c": 10,
      "vitamin_a": 30,
      "fiber": 0.9,
  },
  {
      "name": "レタス",
      "calorie": 14,
      "vitamin_c": 15,
      "vitamin_a": 30,
      "fiber": 1.0,
  },
  {
      "name": "たけのこ",
      "calorie": 24,
      "vitamin_c": 10,
      "vitamin_a": 300,
      "fiber": 2.0,
  },
  {
      "name": "いんげん",
      "calorie": 32,
      "vitamin_c": 10,
      "vitamin_a": 60,
      "fiber": 1.2,
  },
  {
      "name": "さやえんどう",
      "calorie": 36,
      "vitamin_c": 10,
      "vitamin_a": 70,
      "fiber": 2.0,
  },
]
